### Properties ###
GET {{baseUrl}}/api/properties HTTP/1.1
content-type: application/json

### Categories ###
GET {{baseUrl}}/api/categories HTTP/1.1
content-type: application/json

### Photos ###
GET {{baseUrl}}/api/photos HTTP/1.1
content-type: application/json
