### Photos ###
GET {{baseUrl}}/api/photos?page=0&size=2 HTTP/1.1
content-type: application/json

### Photos by ID ###
GET {{baseUrl}}/api/photos/2 HTTP/1.1
content-type: application/json

### Add Photo ###
POST {{baseUrl}}/api/photos HTTP/1.1
content-type: application/json

{
    "url": "Some url"
}

### Assign Photo to Property ###
POST {{baseUrl}}/api/photos/assign HTTP/1.1
content-type: application/json

{
    "photoId": 4,
    "propertyId": 1
}

### Update Photo ###
PUT {{baseUrl}}/api/photos/1 HTTP/1.1
content-type: application/json

{
    "url": "new text",
}

### Delete Photo ###
DELETE {{baseUrl}}/api/photos/4 HTTP/1.1
content-type: application/json